# Generated by Django 2.2.12 on 2021-12-07 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_albuma', models.CharField(max_length=50)),
                ('datum_izdavanja_albuma', models.DateField()),
                ('dodatne_informacije_albuma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Izvodac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izvodac_ime', models.CharField(max_length=50)),
                ('izvodac_prezime', models.CharField(max_length=50)),
                ('datum_rođenja', models.DateField()),
                ('dodatne_informacije_izvodaca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pjesma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_pjesme', models.CharField(max_length=50)),
                ('datum_izdavanja_pjesme', models.DateField()),
                ('trajanje_pjesme', models.CharField(max_length=50)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Album')),
                ('izvodac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Izvodac')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='izvodac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Izvodac'),
        ),
    ]
