# Generated by Django 2.2.12 on 2021-12-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='dodatne_informacije_albuma',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='izvodac',
            name='dodatne_informacije_izvodaca',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
