# Generated by Django 2.2.12 on 2021-12-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211207_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pjesma',
            name='izvodac',
        ),
    ]
