# Generated by Django 2.2.12 on 2022-02-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_pjesma_izvodac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='godina_izdavanja_albuma',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pjesma',
            name='godina_izdavanja_pjesme',
            field=models.CharField(max_length=4),
        ),
    ]
